[project]
name = "steam-crawl"
version = "0.1.0"
description = "Project that collects information about Steam games through the SteamSPY API and Steam's Store API"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.2",
    "requests>=2.32.5",
]
